d /run/webex-config-deploy 0750 root webex-config-pull -
f /run/webex-config-deploy/deploy-config.lock 0660 root webex-config-pull -
d /run/webex-config-pull 0750 webex-config-deploy webex-config-pull -
d /var/lib/webex-generic-account-bot/config-prepare-checkout 0700 webex-config-deploy webex-config-pull -
d /var/lib/webex-generic-account-bot/config-staging 0700 webex-config-deploy webex-config-pull -
