[Unit]
Requires=webex-codex-activation-renew.service
After=webex-codex-activation-renew.service

[Service]
SupplementaryGroups=webex-codex-launch
ReadWritePaths=/var/lib/webex-generic-account-bot/codex-input-staging/pending
