#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const REPO_ROOT = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));
const ENVIRONMENT_NAME = /^[A-Za-z0-9_-]+$/;

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const rendered = await renderEnvironment(options.environment, options.sourceRoot, {
    maxBytes: options.maxBytes,
  });
  assertNoSecrets(rendered);
  assertMaxRenderedBytes(rendered, options.maxBytes);

  process.stdout.write(rendered);
}

export async function renderEnvironment(environment, sourceRoot = REPO_ROOT, options = {}) {
  validateEnvironmentName(environment);
  const budget = new RenderBudget(options.maxBytes);
  const root = await fs.realpath(path.resolve(sourceRoot));
  const environmentDir = path.resolve(root, environment);
  await assertPathInsideRoot(environmentDir, root, `${environment} environment directory`);
  const basePath = path.join(environmentDir, 'bot.toml');
  const spacesDir = path.join(environmentDir, 'spaces');

  await assertPathInsideRoot(basePath, root, `${environment} base config`);
  await assertPathInsideRoot(spacesDir, root, `${environment} spaces directory`);
  const base = await readRequiredFile(basePath, budget);
  const spaceFiles = (await fs.readdir(spacesDir))
    .filter((file) => file.endsWith('.toml'))
    .sort((left, right) => (left < right ? -1 : left > right ? 1 : 0));

  if (spaceFiles.length === 0) {
    throw new Error(`no space config files found in ${spacesDir}`);
  }

  const sections = [
    '# Generated by scripts/render-config.mjs. Do not edit this file directly.',
    `# Source environment: ${environment}`,
    '',
    trimTrailingWhitespace(base),
  ];

  for (const file of spaceFiles) {
    const sourcePath = path.join(spacesDir, file);
    await assertPathInsideRoot(sourcePath, root, `space config ${file}`);
    sections.push(
      '',
      `# Source: ${path.relative(root, sourcePath)}`,
      trimTrailingWhitespace(await readRequiredFile(sourcePath, budget)),
    );
  }

  return `${sections.join('\n')}\n`;
}

export function validateEnvironmentName(environment) {
  if (!ENVIRONMENT_NAME.test(environment)) {
    throw new Error(`environment must be a simple directory name: ${environment}`);
  }
}

export function assertNoSecrets(contents) {
  const forbiddenAssignments =
    /^\s*(access_token|refresh_token|client_secret|bot_token|password)\s*=/gim;
  const privateKey = /-----BEGIN [A-Z ]*PRIVATE KEY-----/;

  const assignment = forbiddenAssignments.exec(contents);
  if (assignment) {
    throw new Error(`possible secret assignment found: ${assignment[1]}`);
  }
  if (privateKey.test(contents)) {
    throw new Error('private key material found');
  }
}

export function assertMaxRenderedBytes(contents, maxBytes) {
  if (!maxBytes) {
    return;
  }
  const size = Buffer.byteLength(contents, 'utf8');
  if (size > maxBytes) {
    throw new Error(`rendered config exceeds max bytes: ${size} > ${maxBytes}`);
  }
}

function parseArgs(args) {
  const options = {
    environment: 'production',
    sourceRoot: REPO_ROOT,
    maxBytes: null,
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--env') {
      options.environment = requiredValue(args, (index += 1), arg);
    } else if (arg === '--out') {
      throw new Error('--out is not supported; use validate-config.sh --out for safe installs');
    } else if (arg === '--source-root') {
      options.sourceRoot = path.resolve(requiredValue(args, (index += 1), arg));
    } else if (arg === '--max-bytes') {
      options.maxBytes = parsePositiveInteger(requiredValue(args, (index += 1), arg), arg);
    } else if (arg === '--stdout') {
      continue;
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }

  return options;
}

function parsePositiveInteger(value, flag) {
  if (!/^[0-9]+$/.test(value)) {
    throw new Error(`${flag} requires a positive integer`);
  }
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    throw new Error(`${flag} requires a positive integer`);
  }
  return parsed;
}

function requiredValue(args, index, flag) {
  const value = args[index];
  if (!value || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
}

class RenderBudget {
  constructor(maxBytes) {
    this.maxBytes = maxBytes;
    this.bytesRead = 0;
  }

  async reserve(file) {
    if (!this.maxBytes) {
      return;
    }
    const stat = await fs.stat(file);
    this.bytesRead += stat.size;
    if (this.bytesRead > this.maxBytes) {
      throw new Error(`rendered config source exceeds max bytes: ${this.bytesRead} > ${this.maxBytes}`);
    }
  }
}

async function readRequiredFile(file, budget = null) {
  try {
    await budget?.reserve(file);
    return await fs.readFile(file, 'utf8');
  } catch (error) {
    throw new Error(`failed to read ${file}: ${error.message}`);
  }
}

async function assertPathInsideRoot(file, root, label) {
  const realFile = await fs.realpath(file);
  const relative = path.relative(root, realFile);
  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new Error(`${label} escapes source root: ${file}`);
  }
}

function trimTrailingWhitespace(contents) {
  return contents
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .join('\n')
    .trim();
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
