#!/usr/local/libexec/webex-host-release/busybox sh
# shellcheck shell=dash
set -eu

exec /usr/local/libexec/webex-host-release/busybox env -i \
  HOME=/ \
  LANG=C \
  LC_ALL=C \
  PATH=/usr/bin:/bin \
  /usr/bin/node \
  /usr/local/libexec/webex-host-release/build-host-release.mjs \
  "$@"
